/*
 * AMD PSP emulation
 *
 * Copyright (C) 2020 Robert Buhren <robert@robertbuhren.de>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
#include "qemu/osdep.h"
#include "qemu/log.h"
#include "hw/arm/psp-sts.h"
#include "trace.h"

/* From PSPEmu: https://github.com/PSPReverse/psp-includes/blob/6fce7ed412fe8678d1f7bea7ee3ae079bde056a7/psp-fw/err.h#L30
 * and: https://dlsvr04.asus.com.cn/pub/ASUS/server/RS720-E9-RS12-E/Manual/E14000_RS720-E9_SERIES_UM_WEB.pdf
 */
static const char * psp_sts_str_tbl[] = {
    "SUCCESS",
    "GENERAL_ERROR",
    "GENERAL_MEMORY_ERROR",
    "BUFFER_OVERFLOW",
    "INVALID_PARAMETER",
    "INVALID_DATA_LENGTH",
    "INVALID_DATA_ALIGNMENT",
    "INVALID_NULL_POINTER",
    "UNUSED_08h",
    "UNUSED_09h",
    "INVALID_ADDRESS",
    "OUT_OF_RESOURCE",
    "TIMEOUT",
    "DATA_ABRT_EXCEPTION",
    "PREFETCH_ABRT_EXCEPTION",
    "OUT_OF_BOUNDS",
    "DATA_CORRUPTION",
    "INVALID_COMMAND",
    "INVALID_PACKAGE_TYPE_FROM_BR",
    "FW_HDR_RETRIEVAL_FAILED_DURING_VALIDATION",
    "KEY_SIZE_NOT_SUPPORTED",
    "AGESA0_VERIFICATION_FAILED",
    "SMU_FW_VERIFICATION_FAILED",
    "OEM_SIGNING_KEY_VERIFICATION_FAILED",
    "GENERIC_FW_VALIDATION_FAILED",
    "RSA_OPERATION_FAILED_BOOTLOADER",
    "CCP_PASSTHROUGH_OPERATION_FAILED",
    "AES_OPERATION_FAILED",
    "CCP_STATE_SAVE_FAILED",
    "CCP_STATE_RESTORE_FAILED",
    "SHA256_OPERATION_FAILED",
    "ZLIB_DECOMPRESSION_FAILED",
    "HMAC_SHA256_OPERATION_FAILED",
    "BOOT_SOURCE_NOT_RECOGNIZED_BY_PSP",
    "PSP_DIRECTORY_ENTRY_NOT_FOUND",
    "SET_WRITE_ENABLE_LATCH_FAILED",
    "PSP_TIMED_OUT_SPIROM_TOOK_TOO_LONG",
    "BIOS_DIRECTORY_NOT_FOUND",
    "SPIROM_INVALID",
    "SLAVE_SEC_STATE_DIFFERS_FROM_MASTER",
    "SMI_INTERFACE_INIT_FAILED",
    "SMI_INTERFACE_GENERIC_ERROR",
    "DIE_ID_INVALID_FOR_EXEC_MCM_FUNC",
    "MCM_CFG_READ_FROM_BOOTROM_INVALID",
    "BOOT_MODE_INVALID",
    "NVSTOR_INIT_FAILED",
    "NVSTOR_GENERIC_ERROR",
    "MCM_ERROR_SLAVE_HAS_MORE_DATA_TO_SEND",
    "MCM_ERROR_32BYTES_EXCEEDED",
    "MCM_SVC_CALL_CLIENT_ID_INVALID",
    "MCM_SLAVE_STATUS_REG_INVALID_BITS",
    "MCM_SVC_CALL_IN_SINGLE_DIE_ENV",
    "PSP_SECURE_MAPPED_TO_INVALID_SEGMENT",
    "NO_PHYSICAL_X86_CORES_ON_DIE",
    "INSUFFICIENT_SPACE_FOR_SECURE_OS",
    "SYSHUB_MAPPING_MEMORY_TARGET_NOT_SUPPORTED",
    "TLB_UNMAP_ATTEMPT_TO_PSP_SECURE_REGION",
    "SMN_ADDRESS_TO_AXI_SPACE_MAPPING_FAILED",
    "SYSHUB_ADDRESS_TO_AXI_SPACE_MAPPING_FAILED",
    "INCONSISTENT_CCX_OR_CORE_COUNT_FROM_BOOTROM",
    "UNCOMPRESSED_IMAGE_SIZE_MISMATCH_FROM_HEADER",
    "COMPRESSION_OPTION_NOT_SUPPORTED",
    "FUSE_INFO_MISMATCH_ON_DIES",
    "SMU_REPORTED_ERROR_FOR_MESSAGE",
    "RUNPOSTX86RELEASEUNITTESTS_FAILED_IN_MEMCMP",
    "PSP_INTERFACE_TO_SMU_NOT_FOUND",
    "TIMER_WAIT_PARAMETER_TOO_LARGE",
    "TEST_HARNESS_MODULE_ERROR",
    "X86_C2PMSG0_WRITE_INTERRUPTED_PSP",
    "L3_REGISTER_WRITE_FAILED",
    "MINI_BL",
    "MINI_BL_CCP_HMAC_UNIT_TEST_FAILED",
    "MINI_BL_POTENTIAL_STACK_CORRUPTION_DETECTED",
    "AGESA_APOB_SVC_CALL_LOADING_AND_VALIDATION_FAILED",
    "DIAG_BL_INCORRECT_BITS_SET",
    "AGESA_MISSED_CALLING_UMCPROGRAMKEYS",
    "SECURE_UNLOCK_ERROR",
    "SYSHUB_REGISTER_PROGRAMMING_MISMATCH_DURING_READBACK",
    "INCORRECT_FAMILY_ID_IN_MP0_SFUSE_SEC",
    "FUNCTION_CAN_ONLY_GET_INVOKED_BY_GM",
    "ACQUIRING_HOST_CTRL_SEM_TO_CLAIM_SMB_OWNERSHIP_FAILED",
    "WAITING_FOR_HOST_COMPLETING_PENDING_XACT_TIMED_OUT",
    "WAITING_FOR_SLAVE_COMPLETING_PENDING_XACT_TIMED_OUT",
    "CANT_KILL_CURRENT_XACT_ON_HOST",
    "ILLEGAL_COMMAND",
    "SMBUS_XACT_COLLISION_DETECTED",
    "XACT_START_OR_PROCESSING_FAILED_BY_HOST",
    "SMBUS_UNSOLICITED_INTERRUPT",
    "PSP_SMU_MESSAGE_UNSUPPORTED",
    "SMU_RESPONSE_ERROR_OR_DATA_CORRUPTION_DETECTED",
    "MCM_STEADY_STATE_UNIT_TEST_FAILED",
    "S3_ENTER_FAILED",
    "AGESA_BL_FAILED_TO_SET_PSP_SMU_RSVD_ADDRESS_VIA_SVC_CALL",
    "UNUSED_5dh",
    "CCX_SEC_BISI_EM_NOT_SET_IN_FUSE_RAM",
    "UNEXPECTED_RESULT_RECEIVED",
    "VMG_STOR_INIT_FAILED",
    "MBED_TLS_USER_APP_FAILED",
    "SMN_FUSE_REGISTER_MAPPING_FAULED",
    "FUSE_BURN_OP_FAILED_DUE_TO_INTERNAL_SOC_ERROR",
    "FUSE_SENSE_OP_TIMED_OUT",
    "FUSE_BURN_OP_TIMED_OUT_WAITING_FOR_BURN_DONE",
    "SECURE_OS_FAILURE",
    "PSP_FW_REVOKED",
    "MODEL_VENDOR_ID_FUSE_VS_BIOS_PUBKEY_TOKEN_MISMATCH",
    "BIOS_OEM_PUBKEY_REVOKED_FOR_PLATFORM",
    "PSP_LVL2_DIR_VALUE_UNEXPECTED",
    "BIOS_LVL2_DIR_VALUE_UNEXPECTED",
    "HVB_VALIDATION_FOR_BIOS_RTM_VOLUME_FAILED",
    "CCP_HAL_INIT_FAILED",
    "UNUSED_6eh",
    "UNUSED_6fh",
    "UNUSED_70h",
    "UNUSED_71h",
    "UNUSED_72h",
    "UNUSED_73h",
    "UNUSED_74h",
    "UNUSED_75h",
    "UNUSED_76h",
    "UNUSED_77h",
    "UNUSED_78h",
    "UNUSED_79h",
    "UNUSED_7ah",
    "UNUSED_7bh",
    "UNUSED_7ch",
    "UNUSED_7dh",
    "UNUSED_7eh",
    "UNUSED_7fh",
    "UNUSED_80h",
    "UNUSED_81h",
    "UNUSED_82h",
    "UNUSED_83h",
    "UNUSED_84h",
    "UNUSED_85h",
    "UNUSED_86h",
    "UNUSED_87h",
    "UNUSED_88h",
    "UNUSED_89h",
    "UNUSED_8ah",
    "UNUSED_8bh",
    "UNUSED_8ch",
    "UNUSED_8dh",
    "UNUSED_8eh",
    "UNUSED_8fh",
    "UNUSED_90h",
    "UNUSED_91h",
    "UNUSED_92h",
    "UNUSED_93h",
    "KNOLL_IDLE_AFTER_RESET_FAILED",
    "KNOLL_BAD_STATUS_FROM_I2CKNOLLCHECK",
    "KNOLL_NACK_ON_GENERAL_CALL_NO_KNOLL_DEV_ON_I2C_BUS",
    "KNOLL_INVALID_NULL_POINTE_TO_I2CKNOLLCHECK",
    "KNOLL_INVALID_DEVICE_ID_DURING_AUTHENTICATION",
    "KNOLL_PROM_KEY_DERIV_FAILED",
    "CRYPTO_INVALID_NULL_POINTER",
    "KNOLL_PROM_KEYS_INVALID_CHKSUM_INVALID",
    "KNOLL_RESPONSE_INVALID_FOR_COMMAND",
    "KNOLL_SEND_COMMAND_FAILED",
    "KNOLL_DEVICE_NOT_FOUND_BY_VERIFIYING_MAC",
    "UNUSED_9fh",
    "BOOTLOADER_SUCCESSFULLY_ENTERED_C_MAIN",
    "C2P_MASTER_INITIALIZED_SLAVE_WAITED_FOR_MASTER",
    "HMAC_KEY_DERIVED_SUCCESSFULLY",
    "MASTER_GOT_BOOT_MODE_AND_SENT_TO_ALL_SLAVES",
    "SPIROM_INITIALIZED_SUCCESSFULLY",
    "BIOS_DIRECTORY_READ_FROM_SPI_TO_SRAM",
    "EARLY_UNLOCK_CHECK",
    "INLINE_AES_KEY_DERIVED_SUCCESSFULLY",
    "INLINE_AES_KEY_PROGRAMMING_DONE",
    "INLINE_AES_KEY_WRAPPER_DERIVATION_DONE",
    "BOOTLOADER_LOADED_HW_IP_CFG_VALUES_SUCCESSFULLY",
    "BOOTLOADER_PROGRAMMED_MBAT_TABLE_SUCCESSFULLY",
    "BOOTLOADER_LOADED_SMU_FW_SUCCESSFULLY",
    "PSP_AND_SMU_CONFIGURED_WAFFLE",
    "USR_MODE_TEST_HARNESS_COMPLETED_SUCCESSFULLY",
    "BOOTLOADER_LOADED_AGESA0_FROM_SPIROM_SUCCESSFULLY",
    "AGESA_PHASE_COMPLETED",
    "RUN_POST_DRAM_TRAINING_TESTS_COMPLETED_SUCCESSFULLY",
    "SMU_FW_LOADED_TO_SMU_SECURE_RAM_SUCCESSFULLY",
    "SENT_ALL_REQUIRED_BOOT_TIME_MESSAGES_TO_SMU",
    "SECURITY_GASKET_BINARY_VALIDATED_AND_EXECUTED",
    "UMC_KEYS_GENERATED_AND_PROGRAMMED",
    "INLINE_AES_KEY_WRAPPER_STORED_IN_DRAM",
    "FW_VALIDATION_COMPLETED",
    "FW_VALIDATION_2_COMPLETED",
    "BIOS_COPY_FROM_SPI_TO_DRAM_COMPLETE",
    "FW_VALIDATION_3_COMPLETED",
    "BIOS_LOAD_PROCESS_COMPLETED",
    "BOOTLOADER_RELEASED_X86_SUCCESSFULLY",
    "EARLY_SECURE_DEBUG_COMPLETED",
    "GET_FW_VERSION_CMD_RECVD_FROM_BIOS_COMPLETED",
    "SMI_INFO_CMD_RECVD_FROM_BIOS_COMPLETED",
    "WARM_BOOT_RESUME_ENTERED_SUCCESSFULLY",
    "COPIED_SECUREOS_TO_SRAM_SUCCESSFULLY",
    "COPIED_TRUSTLETS_TO_PSP_SECURE_MEMORY_SUCCESSFULLY",
    "ABOUT_TO_JUMP_TO_SECUREOS",
    "CCP_AND_UMC_STATE_RESTORED_SUCCESSFULLY_ON_S3_RESUME",
    "MINI_BL_PSP_SRAM_HMAC_VALIDATED_SUCCESSFULLY",
    "MINI_BL_ABOUT_TO_JUMP_TO_T_BASE",
    "VMG_ECDH_UNIT_TEST_STARTED",
    "VMG_ECDH_UNIT_TEST_PASSED",
    "VMG_ECC_CDH_PRIMITIVE_UNIT_TEST_STARTED",
    "VMG_ECC_CDH_PRIMITIVE_UNIT_TEST_PASSED",
    "VMG_SP800_108_KDF_CTR_HMAC_UNIT_TEST_STARTED",
    "VMG_SP800_108_KDF_CTR_HMAC_UNIT_TEST_PASSED",
    "VMG_LAUNCH_TEST_STARTED",
    "VMG_LAUNCH_TEST_PASSED",
    "MP1_TAKEN_OUT_OF_RESET",
    "PSP_AND_SMU_RESERVED_ADDRESS_CORRECT",
    "NAPLES_STEADY_STATE_WFI_LOOP_REACHED",
    "KNOLL_DEVICE_INITIALIZED_SUCCESSFULLY",
    "KNOLL_32BYTE_RAND_OUT_RETURNED_SUCCESSFULLY",
    "KNOLL_32BYTE_MAC_RECEIVED_SUCCESSFULLY",
    "KNOLL_DEVICE_VERIFIED_SUCCESSFULLY",
    "KNOLL_DEVICE_POWER_ON_DONE",
    "RECOVERY_MODE_ENTERED_DUE_TO_TRUSTLET_VALIDATION_FAIL",
    "RECOVERY_MODE_ENTERED_DUE_TO_OS_VALIDATION_FAIL",
    "RECOVERY_MODE_ENTERED_DUE_TO_OEM_PUBKEY_NOT_FOUND"
};
#define psp_sts_str_tbl_size  ( sizeof(psp_sts_str_tbl) / sizeof(*psp_sts_str_tbl) )
const char * psp_sts_str_tbl_oor = "INVALID_OUT_OF_RANGE";
#define psp_sts_str_get(X) ( X < psp_sts_str_tbl_size ? psp_sts_str_tbl[X] : psp_sts_str_tbl_oor )

static uint64_t psp_sts_read(void *opaque, hwaddr offset, unsigned int size) {
    PSPStsState *s = PSP_STS(opaque);
    trace_psp_sts_read(s->psp_sts_val, psp_sts_str_get(s->psp_sts_val));
    return s->psp_sts_val;
}

static void psp_sts_write(void *opaque, hwaddr offset,
                       uint64_t value, unsigned int size) {
    PSPStsState *s = PSP_STS(opaque);
    s->psp_sts_val = value;
    trace_psp_sts_write(value, psp_sts_str_get(s->psp_sts_val));
}

static const MemoryRegionOps sts_mem_ops = {
    .read = psp_sts_read,
    .write = psp_sts_write,
    .endianness = DEVICE_LITTLE_ENDIAN,
    .valid.min_access_size = 4,
    .valid.max_access_size = 4,
};

static void psp_sts_realize(DeviceState *dev, Error **errp) {

    PSPStsState *s = PSP_STS(dev);
    SysBusDevice *sbd = SYS_BUS_DEVICE(dev);

    s->psp_sts_val = 0;

    memory_region_init_io(&s->iomem, OBJECT(dev), &sts_mem_ops, s,
            TYPE_PSP_STS, 4);

    sysbus_init_mmio(sbd, &s->iomem);
}

static void psp_sts_class_init(ObjectClass * klass, void * data) {
    DeviceClass * dc = DEVICE_CLASS(klass);

    dc->realize = psp_sts_realize;
}

static const TypeInfo psp_sts_info = {
    .name = TYPE_PSP_STS,
    .parent = TYPE_SYS_BUS_DEVICE,
    .instance_size = sizeof(PSPStsState),
    .class_init = psp_sts_class_init,
};

static void psp_sts_register_types(void) {
    type_register_static(&psp_sts_info);

}
type_init(psp_sts_register_types);
